export const API_TAGS = {
    WAITLIST: "Waitlist"
} as const;

// Waitlist Error Messages
export const WAITLIST_ERRORS = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
    INVALID_REFERRAL_CODE: "INVALID_REFERRAL_CODE",
    INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",
    VERIFICATION_TOKEN_EXPIRED: "VERIFICATION_TOKEN_EXPIRED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_OR_USERID_REQUIRED: "EMAIL_OR_USERID_REQUIRED",
} as const;

// Points system
export const POINTS_PER_REFERRAL = 10;